/* $Id: ScriptConstants.cpp,v 1.4 2005/02/08 18:59:19 wiz Exp $ */
//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "OrionScriptInterface.h"
#include "ScriptConstants.h"
#include "ScriptBasic.h"
#include "HostMask.h"

//---------------------------------------------------------------------------
#pragma package(smart_init)

#if SCRIPTING

//---------------------------------------------------------------------------
void ScriptConstants::Register( TSRMLS_DC )
{
    REGISTER_MAIN_LONG_CONSTANT( "mrNone", mrNone, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrOk", mrOk, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrCancel", mrCancel, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrAbort", mrAbort, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrRetry", mrRetry, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrIgnore", mrIgnore, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrYes", mrYes, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrNo", mrNo, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mrAll", mrAll, CONST_CS | CONST_PERSISTENT );

    REGISTER_MAIN_LONG_CONSTANT( "mtWarning", mtWarning, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mtError", mtError, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mtInformation", mtInformation, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mtConfirmation", mtConfirmation, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mtCustom", mtCustom, CONST_CS | CONST_PERSISTENT );

    REGISTER_MAIN_LONG_CONSTANT( "mbYes", BIT( mbYes ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbNo", BIT( mbNo ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbOK", BIT( mbOK ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbCancel", BIT( mbCancel ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbHelp", BIT( mbHelp ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbAbort", BIT( mbAbort ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbRetry", BIT( mbRetry ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbIgnore", BIT( mbIgnore ), CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "mbAll", BIT( mbAll ), CONST_CS | CONST_PERSISTENT );

    REGISTER_MAIN_LONG_CONSTANT( "SE_ACTION", SE_ACTION, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_ACTIVE", SE_ACTIVE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_APPACTIVE", SE_APPACTIVE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_BAN", SE_BAN, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_CHAT", SE_CHAT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_CLOSE", SE_CLOSE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_CONNECT", SE_CONNECT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_CONNECTFAIL", SE_CONNECT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_CTCP", SE_CTCP, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_CTCPREPLY", SE_CTCPREPLY, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_DCC", SE_DCC, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_DEOP", SE_DEOP, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_DEVOICE", SE_DEVOICE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_DISCONNECT", SE_DEVOICE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_ERROR", SE_ERROR, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_EXIT", SE_EXIT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_FILERCVD", SE_FILERCVD, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_FILESENT", SE_FILESENT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_GETFAIL", SE_GETFAIL, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_INPUT", SE_INPUT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_INVITE", SE_INVITE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_JOIN", SE_JOIN, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_KICK", SE_KICK, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_LOGON", SE_LOGON, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_MODE", SE_MODE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_NICK", SE_NICK, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_NOTICE", SE_NOTICE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_NOTIFY", SE_NOTIFY, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_OP", SE_OP, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_OPEN", SE_OPEN, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_PART", SE_PART, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_PING", SE_PING, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_PONG", SE_PONG, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_QUIT", SE_QUIT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_RAW", SE_RAW, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_SENDFAIL", SE_SENDFAIL, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_SIGNAL", SE_SIGNAL, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_SNOTICE", SE_SNOTICE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_TEXT", SE_TEXT, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_TOPIC", SE_TOPIC, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_UNBAN", SE_UNBAN, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_USERMODE", SE_USERMODE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_VOICE", SE_VOICE, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "SE_WALLOPS", SE_WALLOPS, CONST_CS | CONST_PERSISTENT );

    REGISTER_MAIN_LONG_CONSTANT( "MASK_NICK_USER_HOST", MASK_NICK_USER_HOST, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "MASK_NICK_USER_TLD", MASK_NICK_USER_TLD, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "MASK_USER_HOST", MASK_USER_HOST, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "MASK_USER_TLD", MASK_USER_TLD, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "MASK_HOST", MASK_HOST, CONST_CS | CONST_PERSISTENT );
    REGISTER_MAIN_LONG_CONSTANT( "MASK_TLD", MASK_TLD, CONST_CS | CONST_PERSISTENT );
}
//---------------------------------------------------------------------------
#endif /* SCRIPTING */
//---------------------------------------------------------------------------

